version: "3.9"

services:
  api:
    build: .
    container_name: go_tasks_api
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./db:/app/db
      - ./videos:/app/videos
    environment:
      - TZ=Asia/Tashkent
    networks:
      - go_network

networks:
  go_network:
    driver: bridge
